[package]
name = "trombinoscope"
version = "0.1.0"
edition = "2021"
default-run = "trombinoscope_poster"

[dependencies]
encoding = "0.2.33"
image = "0.25.5"
imagesize = "0.13"
pdfium-render = "0.8.29"
rand = "0.8.5"
regex = "1.11.1"
unicode-normalization = "0.1.24"
zip = "2.2.2"
