[package]
name = "trombinoscope"
version = "0.1.0"
edition = "2021"
default-run = "trombinoscope_poster"

[dependencies]
encoding = "0.2.33"
image = "0.25.5"
pdfium-render = "0.8.27"
rand = "0.8.5"
zip = "2.2.2"
