[package]
name = "trombinoscope"
version = "0.1.0"
edition = "2021"
default-run = "trombinoscope_poster"

[dependencies]
encoding = "0.2.33"
fast_image_resize = "5.1.2"
image = "0.25.5"
pdfium-render = "0.8.29"
rand = "0.8.5"
turbojpeg = "1.2.2"
zip = "2.2.2"
